In [1]:
import numpy as np

In [7]:
# NUMPY CONCATENATE
x = np.array([[1,2],[3,4]])  
y = np.array([[12,30]])  
z = np.concatenate((x,y))  
print(z)

# Generating a random 3 x 4 matrix
X = np.random.randint(low=0, high=10, size=(3, 4))
print(f"X before:\n {X}")
# column of ones
# len(X) = number of rows in X
ones = np.ones(len(X)).reshape(len(X), 1)

# add the column of ones along y-axis 
# assertEqual(len(X), len(ones))
X = np.concatenate((ones, X), axis = 1)
print(np.array(X))

[[ 1  2]
 [ 3  4]
 [12 30]]
X before:
 [[2 7 1 4]
 [4 9 6 2]
 [6 2 6 5]]
[[1. 2. 7. 1. 4.]
 [1. 4. 9. 6. 2.]
 [1. 6. 2. 6. 5.]]
